import { EntityType, UnitStats } from './types';

export const GAME_WIDTH = 2000;
export const GAME_HEIGHT = 2000;
export const FPS = 60;

export const STATS: Record<EntityType, UnitStats> = {
  [EntityType.WORKER]: {
    cost: 50,
    hp: 45,
    damage: 5,
    range: 20,
    vision: 300,
    speed: 2.5,
    attackSpeed: 45,
    buildTime: 200,
    width: 10,
    height: 10,
    supplyCost: 1,
    supplyProvided: 0,
  },
  [EntityType.MARINE]: {
    cost: 50,
    hp: 40,
    damage: 6,
    range: 120,
    vision: 400,
    speed: 2.8,
    attackSpeed: 30,
    buildTime: 300,
    width: 12,
    height: 12,
    supplyCost: 1,
    supplyProvided: 0,
  },
  [EntityType.MEDIC]: {
    cost: 75,
    hp: 60,
    damage: 0,
    range: 100, // Heal range
    vision: 400,
    speed: 2.8,
    attackSpeed: 40, // Heal cooldown
    buildTime: 400,
    width: 12,
    height: 12,
    supplyCost: 1,
    supplyProvided: 0,
    healRate: 5
  },
  [EntityType.BASE]: {
    cost: 400,
    hp: 1500,
    damage: 0,
    range: 0,
    vision: 500,
    speed: 0,
    attackSpeed: 0,
    buildTime: 0,
    width: 60,
    height: 60,
    supplyCost: 0,
    supplyProvided: 10,
  },
  [EntityType.BARRACKS]: {
    cost: 150,
    hp: 1000,
    damage: 0,
    range: 0,
    vision: 400,
    speed: 0,
    attackSpeed: 0,
    buildTime: 500,
    width: 50,
    height: 50,
    supplyCost: 0,
    supplyProvided: 0,
  },
  [EntityType.BUNKER]: {
    cost: 100,
    hp: 400,
    damage: 0, // Relies on garrison
    range: 140, // slightly more than marine
    vision: 350,
    speed: 0,
    attackSpeed: 30, // Base attack speed for bunker logic
    buildTime: 400,
    width: 40,
    height: 40,
    supplyCost: 0,
    supplyProvided: 0,
  },
  [EntityType.SUPPLY_DEPOT]: {
    cost: 100,
    hp: 500,
    damage: 0,
    range: 0,
    vision: 300,
    speed: 0,
    attackSpeed: 0,
    buildTime: 400,
    width: 30,
    height: 30,
    supplyCost: 0,
    supplyProvided: 8,
  },
  [EntityType.MINERAL]: {
    cost: 0,
    hp: 9999,
    damage: 0,
    range: 0,
    vision: 0,
    speed: 0,
    attackSpeed: 0,
    buildTime: 0,
    width: 25,
    height: 15,
    supplyCost: 0,
    supplyProvided: 0,
  },
  [EntityType.MOUNTAIN]: {
    cost: 0,
    hp: 99999,
    damage: 0,
    range: 0,
    vision: 0,
    speed: 0,
    attackSpeed: 0,
    buildTime: 0,
    width: 80,
    height: 80,
    supplyCost: 0,
    supplyProvided: 0,
  },
  [EntityType.WATER]: {
    cost: 0,
    hp: 99999,
    damage: 0,
    range: 0,
    vision: 0,
    speed: 0,
    attackSpeed: 0,
    buildTime: 0,
    width: 60,
    height: 60,
    supplyCost: 0,
    supplyProvided: 0,
  },
};

export const INITIAL_RESOURCES = 50;
export const RESOURCE_GATHER_AMOUNT = 5;
export const RESOURCE_CARRY_CAPACITY = 5;
export const GATHER_TIME = 60; // Frames to gather